//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantPOSFINAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckItemTbl
    {
        public int CheckItemID { get; set; }
        public int CheckNum { get; set; }
        public int ItemID { get; set; }
    
        public virtual CheckIDtbl CheckIDtbl { get; set; }
        public virtual MenuItemTbl MenuItemTbl { get; set; }
    }
}
