//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantPOSFINAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIDtbl
    {
        public CheckIDtbl()
        {
            this.CheckItemTbls = new HashSet<CheckItemTbl>();
        }
    
        public int CheckNum { get; set; }
        public System.DateTime CheckDate { get; set; }
    
        public virtual ICollection<CheckItemTbl> CheckItemTbls { get; set; }
    }
}
